config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :foods
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	has_many :restaurants
	has_many :users, through: :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :user
	belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
	has_many :restaurants
	has_many :foods, through: :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def show
		@foods = Food.find(params[:id])
	end

	def new
		@foods = Food.new
	end

	def create
		@foods = Food.create(food_params)
		redirect_to food_path(@foods)
	end

	def edit
		@foods = Food.find(params[:id])
	end

	def update
		@foods = Food.find(params[:id])
		@foods.update(food_params)
		redirect_to food_path(@foods)
	end


	def destroy
		@foods = Food.find(params[:id])
		@foods.destroy
		redirect_to foods_path
	end

	private
	def food_params
		params.require(:food).permit(:name)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurants = Restaurant.find(params[:id])
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurants = Restaurant.create(rest_params)
		redirect_to restaurant_path(@restaurants)
	end

	def edit
		@restaurants = Restaurant.find(params[:id])
	end

	def update
		@restaurants = Restaurant.find(params[:id])
		@restaurants.update(rest_params)
		redirect_to restaurant_path(@restaurants)
	end

	def destroy
		@restaurants = Restaurant.find(params[:id])
		@restaurants.destroy
		redirect_to restaurants_path
	end

	private
	def rest_params
		params.require(:restaurant).permit(:name, :location, :user_id, :food_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@users = User.find(params[:id])
	end

	def new
		@users = User.new
	end

	def create
		@users = User.create(user_params)
		redirect_to user_path(@users)
	end

	def update
		@users = User.find(params[:id])
		@users.update(user_params)
		redirect_to user_path(@users)
	end

	def edit
		@users = User.find(params[:id])
	end

	def destroy
		@users = User.find(params[:id])
		@users.destroy
		redirect_to users_path
	end
	private
	def user_params
		params.require(:user).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/edit.html.erb
<%=form_for @foods do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/foods/index.html.erb
<% @foods.each do |f| %>
	<div><%= link_to f.name, food_path(f) %></div>
<% end %>

<%=link_to "Create New Food", new_food_path %>

app/views/foods/new.html.erb
<%=form_for @foods do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/foods/show.html.erb
<%= @foods.name %>
<%= link_to "Back to Index", foods_path %>
<%= link_to "Edit this Food", edit_food_path %>
<%= link_to "Delete this Food", food_path, method: "DELETE"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%=form_for @restaurants do |r| %>
	<%= r.label :name %>
	<%= r.text_field :name %>
	<%= r.label :location %>
	<%= r.text_field :location %>
	<%= r.label :user_id %>
	<%= r.collection_select :user_id, User.all, :id, :name %>
	<%= r.label :food_id %>
	<%= r.collection_select :food_id, Food.all, :id, :name %>
	<%= r.submit %>
	<% end %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |r| %>
	<div>name: <%=  link_to r.name, restaurant_path(r) %></div>
	<div>location: <%= r.location %></div>
<% end %>

<%=link_to "Create New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%=form_for @restaurant do |r| %>
	<%= r.label :name %>
	<%= r.text_field :name %>
	<%= r.label :location %>
	<%= r.text_field :location %>
	<%= r.label :user_id %>
	<%= r.collection_select :user_id, User.all, :id, :name %>
	<%= r.label :food_id %>
	<%= r.collection_select :food_id, Food.all, :id, :name %>
	<%= r.submit %>
	<% end %>

app/views/restaurants/show.html.erb
<h3>Our recent customers</h3>
<p><%= link_to @restaurants.user.name, user_path(@restaurants.user) %> enjoys <%= link_to @restaurants.food.name, food_path(@restaurants.food) %></p>
<div><%= link_to "Edit Page", edit_restaurant_path %></div>
<div><%= link_to "Back to Index Page", restaurants_path %></div>
<div><%= link_to "Delete this Restaurant", restaurant_path, method: "DELETE"%></div>

app/views/users/edit.html.erb
<%= form_for @users do |u| %>
	<%= u.label :name %>
	<%= u.text_field :name %>
	<%= u.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div>	<%= link_to user.name, user_path(user) %> </div>
<% end %>
<%= link_to "Create new User", new_user_path%>

app/views/users/new.html.erb
<%= form_for @users do |u| %>
	<%= u.label :name%>
	<%= u.text_field :name%>
	<%= u.submit %>
<% end %>

app/views/users/show.html.erb
<%= @users.name%>
<div><%= link_to "Back to Index", users_path %></div>
<div><%= link_to "Edit User", edit_user_path(@users)%></div>
<div><%= link_to "Delete this User", user_path(@users), method: "DELETE"%></div>